// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssh/ssh.proto

package ssh

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Repository struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Repo                 string   `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5394c6fddbe608, []int{0}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Repository) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

type UploadPackRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Data                 []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UploadPackRequest) Reset()         { *m = UploadPackRequest{} }
func (m *UploadPackRequest) String() string { return proto.CompactTextString(m) }
func (*UploadPackRequest) ProtoMessage()    {}
func (*UploadPackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5394c6fddbe608, []int{1}
}

func (m *UploadPackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadPackRequest.Unmarshal(m, b)
}
func (m *UploadPackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadPackRequest.Marshal(b, m, deterministic)
}
func (m *UploadPackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadPackRequest.Merge(m, src)
}
func (m *UploadPackRequest) XXX_Size() int {
	return xxx_messageInfo_UploadPackRequest.Size(m)
}
func (m *UploadPackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadPackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadPackRequest proto.InternalMessageInfo

func (m *UploadPackRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *UploadPackRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadPackResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadPackResponse) Reset()         { *m = UploadPackResponse{} }
func (m *UploadPackResponse) String() string { return proto.CompactTextString(m) }
func (*UploadPackResponse) ProtoMessage()    {}
func (*UploadPackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5394c6fddbe608, []int{2}
}

func (m *UploadPackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadPackResponse.Unmarshal(m, b)
}
func (m *UploadPackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadPackResponse.Marshal(b, m, deterministic)
}
func (m *UploadPackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadPackResponse.Merge(m, src)
}
func (m *UploadPackResponse) XXX_Size() int {
	return xxx_messageInfo_UploadPackResponse.Size(m)
}
func (m *UploadPackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadPackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadPackResponse proto.InternalMessageInfo

func (m *UploadPackResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReceivePackRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Data                 []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReceivePackRequest) Reset()         { *m = ReceivePackRequest{} }
func (m *ReceivePackRequest) String() string { return proto.CompactTextString(m) }
func (*ReceivePackRequest) ProtoMessage()    {}
func (*ReceivePackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5394c6fddbe608, []int{3}
}

func (m *ReceivePackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceivePackRequest.Unmarshal(m, b)
}
func (m *ReceivePackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceivePackRequest.Marshal(b, m, deterministic)
}
func (m *ReceivePackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceivePackRequest.Merge(m, src)
}
func (m *ReceivePackRequest) XXX_Size() int {
	return xxx_messageInfo_ReceivePackRequest.Size(m)
}
func (m *ReceivePackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceivePackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceivePackRequest proto.InternalMessageInfo

func (m *ReceivePackRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *ReceivePackRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReceivePackResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceivePackResponse) Reset()         { *m = ReceivePackResponse{} }
func (m *ReceivePackResponse) String() string { return proto.CompactTextString(m) }
func (*ReceivePackResponse) ProtoMessage()    {}
func (*ReceivePackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5394c6fddbe608, []int{4}
}

func (m *ReceivePackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceivePackResponse.Unmarshal(m, b)
}
func (m *ReceivePackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceivePackResponse.Marshal(b, m, deterministic)
}
func (m *ReceivePackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceivePackResponse.Merge(m, src)
}
func (m *ReceivePackResponse) XXX_Size() int {
	return xxx_messageInfo_ReceivePackResponse.Size(m)
}
func (m *ReceivePackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceivePackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceivePackResponse proto.InternalMessageInfo

func (m *ReceivePackResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Repository)(nil), "ssh.Repository")
	proto.RegisterType((*UploadPackRequest)(nil), "ssh.UploadPackRequest")
	proto.RegisterType((*UploadPackResponse)(nil), "ssh.UploadPackResponse")
	proto.RegisterType((*ReceivePackRequest)(nil), "ssh.ReceivePackRequest")
	proto.RegisterType((*ReceivePackResponse)(nil), "ssh.ReceivePackResponse")
}

func init() { proto.RegisterFile("ssh/ssh.proto", fileDescriptor_3b5394c6fddbe608) }

var fileDescriptor_3b5394c6fddbe608 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x89, 0x8a, 0xe0, 0xf5, 0xcf, 0x30, 0x82, 0x2b, 0x7b, 0x92, 0x3e, 0x75, 0xc8, 0x5a,
	0x99, 0x7e, 0x02, 0x05, 0xf1, 0xb1, 0xa4, 0x08, 0xea, 0x5b, 0x9a, 0x5d, 0xd6, 0xe2, 0x5c, 0x62,
	0x6e, 0x5a, 0xf0, 0xe3, 0xf8, 0x4d, 0x25, 0xa9, 0x6c, 0xd5, 0xe2, 0x9b, 0x6f, 0x87, 0x9b, 0xcb,
	0xef, 0x9c, 0x13, 0x2e, 0x1c, 0x13, 0x55, 0x19, 0x51, 0x95, 0x1a, 0xab, 0x9d, 0xe6, 0xbb, 0x44,
	0x55, 0x7c, 0x03, 0x20, 0xd0, 0x68, 0xaa, 0x9d, 0xb6, 0x1f, 0x9c, 0xc3, 0x5e, 0x43, 0x68, 0x23,
	0x76, 0xc1, 0x92, 0x03, 0x11, 0xb4, 0x9f, 0x59, 0x34, 0x3a, 0xda, 0xe9, 0x66, 0x5e, 0xc7, 0x4f,
	0x70, 0xfa, 0x68, 0x56, 0x5a, 0x2e, 0x72, 0xa9, 0x5e, 0x05, 0xbe, 0x37, 0x48, 0x8e, 0x67, 0x00,
	0x76, 0x83, 0x0a, 0x88, 0xc3, 0xf9, 0x28, 0xf5, 0x7e, 0x5b, 0x07, 0xd1, 0x5b, 0xf1, 0xe4, 0x85,
	0x74, 0x32, 0x90, 0x8f, 0x44, 0xd0, 0x71, 0x02, 0xbc, 0x4f, 0x26, 0xa3, 0xd7, 0x84, 0x9b, 0x4d,
	0xd6, 0xdb, 0x7c, 0x06, 0x2e, 0x50, 0x61, 0xdd, 0xe2, 0xbf, 0x87, 0x98, 0xc2, 0xd9, 0x0f, 0xf4,
	0xdf, 0x29, 0xe6, 0x9f, 0x0c, 0x78, 0x51, 0x3c, 0xe4, 0xfe, 0x47, 0x95, 0x5e, 0x15, 0x68, 0xdb,
	0x5a, 0x21, 0xbf, 0x83, 0x93, 0x5c, 0x93, 0xdb, 0x56, 0xe1, 0xe7, 0x21, 0xc4, 0xe0, 0xd7, 0x26,
	0xe3, 0xc1, 0xbc, 0x73, 0xbb, 0x62, 0xfc, 0x1e, 0x46, 0x1e, 0xd2, 0x8b, 0xc2, 0xc7, 0xdf, 0x55,
	0x7e, 0xf7, 0x9e, 0x44, 0xc3, 0x87, 0x8e, 0x93, 0xb0, 0xdb, 0xcb, 0x97, 0xe9, 0xb2, 0x76, 0x55,
	0x53, 0xa6, 0x4a, 0xbf, 0x65, 0x6d, 0x2b, 0x9d, 0x5c, 0xcb, 0x12, 0xb3, 0x65, 0xed, 0x66, 0x95,
	0x9c, 0x19, 0xad, 0xb2, 0x70, 0x11, 0xfe, 0x36, 0xca, 0xfd, 0x20, 0xaf, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0xe7, 0x1c, 0xbf, 0x2d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SSHProtocolServiceClient is the client API for SSHProtocolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SSHProtocolServiceClient interface {
	PostUploadPack(ctx context.Context, in *UploadPackRequest, opts ...grpc.CallOption) (SSHProtocolService_PostUploadPackClient, error)
	PostReceivePack(ctx context.Context, opts ...grpc.CallOption) (SSHProtocolService_PostReceivePackClient, error)
}

type sSHProtocolServiceClient struct {
	cc *grpc.ClientConn
}

func NewSSHProtocolServiceClient(cc *grpc.ClientConn) SSHProtocolServiceClient {
	return &sSHProtocolServiceClient{cc}
}

func (c *sSHProtocolServiceClient) PostUploadPack(ctx context.Context, in *UploadPackRequest, opts ...grpc.CallOption) (SSHProtocolService_PostUploadPackClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SSHProtocolService_serviceDesc.Streams[0], "/ssh.SSHProtocolService/PostUploadPack", opts...)
	if err != nil {
		return nil, err
	}
	x := &sSHProtocolServicePostUploadPackClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SSHProtocolService_PostUploadPackClient interface {
	Recv() (*UploadPackResponse, error)
	grpc.ClientStream
}

type sSHProtocolServicePostUploadPackClient struct {
	grpc.ClientStream
}

func (x *sSHProtocolServicePostUploadPackClient) Recv() (*UploadPackResponse, error) {
	m := new(UploadPackResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sSHProtocolServiceClient) PostReceivePack(ctx context.Context, opts ...grpc.CallOption) (SSHProtocolService_PostReceivePackClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SSHProtocolService_serviceDesc.Streams[1], "/ssh.SSHProtocolService/PostReceivePack", opts...)
	if err != nil {
		return nil, err
	}
	x := &sSHProtocolServicePostReceivePackClient{stream}
	return x, nil
}

type SSHProtocolService_PostReceivePackClient interface {
	Send(*ReceivePackRequest) error
	CloseAndRecv() (*ReceivePackResponse, error)
	grpc.ClientStream
}

type sSHProtocolServicePostReceivePackClient struct {
	grpc.ClientStream
}

func (x *sSHProtocolServicePostReceivePackClient) Send(m *ReceivePackRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sSHProtocolServicePostReceivePackClient) CloseAndRecv() (*ReceivePackResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReceivePackResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SSHProtocolServiceServer is the server API for SSHProtocolService service.
type SSHProtocolServiceServer interface {
	PostUploadPack(*UploadPackRequest, SSHProtocolService_PostUploadPackServer) error
	PostReceivePack(SSHProtocolService_PostReceivePackServer) error
}

// UnimplementedSSHProtocolServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSSHProtocolServiceServer struct {
}

func (*UnimplementedSSHProtocolServiceServer) PostUploadPack(req *UploadPackRequest, srv SSHProtocolService_PostUploadPackServer) error {
	return status.Errorf(codes.Unimplemented, "method PostUploadPack not implemented")
}
func (*UnimplementedSSHProtocolServiceServer) PostReceivePack(srv SSHProtocolService_PostReceivePackServer) error {
	return status.Errorf(codes.Unimplemented, "method PostReceivePack not implemented")
}

func RegisterSSHProtocolServiceServer(s *grpc.Server, srv SSHProtocolServiceServer) {
	s.RegisterService(&_SSHProtocolService_serviceDesc, srv)
}

func _SSHProtocolService_PostUploadPack_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UploadPackRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SSHProtocolServiceServer).PostUploadPack(m, &sSHProtocolServicePostUploadPackServer{stream})
}

type SSHProtocolService_PostUploadPackServer interface {
	Send(*UploadPackResponse) error
	grpc.ServerStream
}

type sSHProtocolServicePostUploadPackServer struct {
	grpc.ServerStream
}

func (x *sSHProtocolServicePostUploadPackServer) Send(m *UploadPackResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SSHProtocolService_PostReceivePack_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SSHProtocolServiceServer).PostReceivePack(&sSHProtocolServicePostReceivePackServer{stream})
}

type SSHProtocolService_PostReceivePackServer interface {
	SendAndClose(*ReceivePackResponse) error
	Recv() (*ReceivePackRequest, error)
	grpc.ServerStream
}

type sSHProtocolServicePostReceivePackServer struct {
	grpc.ServerStream
}

func (x *sSHProtocolServicePostReceivePackServer) SendAndClose(m *ReceivePackResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sSHProtocolServicePostReceivePackServer) Recv() (*ReceivePackRequest, error) {
	m := new(ReceivePackRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SSHProtocolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssh.SSHProtocolService",
	HandlerType: (*SSHProtocolServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PostUploadPack",
			Handler:       _SSHProtocolService_PostUploadPack_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PostReceivePack",
			Handler:       _SSHProtocolService_PostReceivePack_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ssh/ssh.proto",
}
