version: '3'
services:

  barracuda:
    build:
      context: ./
      dockerfile: barracuda/Dockerfile
    image: git-ha-poc/barracuda
    container_name: barracuda
    environment:
      DSN: root:deadbeef@tcp(db:3306)/git-ha-poc
      TZ: Asia/Tokyo
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 1
      WAIT_HOST_CONNECT_TIMEOUT: 30
    depends_on:
      - db

  crab:
    build:
      context: ./
      dockerfile: crab/Dockerfile
    image: git-ha-poc/crab
    container_name: crab
    ports:
      - 8080:8080
    environment:
      SWORDFISH_ADDR: swordfish:50051
      TZ: Asia/Tokyo

  flounder:
    build:
      context: ./
      dockerfile: flounder/Dockerfile
    image: git-ha-poc/flounder
    container_name: flounder
    ports:
      - 2222:2222
    environment:
      SWORDFISH_ADDR: swordfish:50051
      TZ: Asia/Tokyo

  swordfish:
    build:
      context: ./
      dockerfile: swordfish/Dockerfile
    image: git-ha-poc/swordfish
    container_name: swordfish
    ports:
      - 50051:50051
    environment:
      DSN: root:deadbeef@tcp(db:3306)/git-ha-poc
      TZ: Asia/Tokyo
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 1
      WAIT_HOST_CONNECT_TIMEOUT: 30
    depends_on:
      - db

  tadpole:
    build:
      context: ./
      dockerfile: tadpole/Dockerfile
    image: git-ha-poc/tadpole
    container_name: tadpolea
    environment:
      TZ: Asia/Tokyo

  tadpole-1-a:
    image: git-ha-poc/tadpole
    container_name: tadpole-1-a
    environment:
      TZ: Asia/Tokyo
  tadpole-2-a:
    image: git-ha-poc/tadpole
    container_name: tadpole-2-a
    environment:
      TZ: Asia/Tokyo
  tadpole-3-b:
    image: git-ha-poc/tadpole
    container_name: tadpole-3-a
    environment:
      TZ: Asia/Tokyo
  tadpole-4-b:
    image: git-ha-poc/tadpole
    container_name: tadpole-4-b
    environment:
      TZ: Asia/Tokyo
  tadpole-5-b:
    image: git-ha-poc/tadpole
    container_name: tadpole-5-b
    environment:
      TZ: Asia/Tokyo
  tadpole-6-a:
    image: git-ha-poc/tadpole
    container_name: tadpole-6-a
    environment:
      TZ: Asia/Tokyo

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: deadbeef
      MYSQL_DATABASE: git-ha-poc
      TZ: Asia/Tokyo
    volumes:
      - ${PWD}/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${PWD}/db/schema:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci