// Code generated by protoc-gen-go. DO NOT EDIT.
// source: replication/replication.proto

package replication

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Repository struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Repo                 string   `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_36da0b8129c7cf1c, []int{0}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Repository) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

type ReplicateRepositoryRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	RemoteAddr           string      `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReplicateRepositoryRequest) Reset()         { *m = ReplicateRepositoryRequest{} }
func (m *ReplicateRepositoryRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicateRepositoryRequest) ProtoMessage()    {}
func (*ReplicateRepositoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36da0b8129c7cf1c, []int{1}
}

func (m *ReplicateRepositoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateRepositoryRequest.Unmarshal(m, b)
}
func (m *ReplicateRepositoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateRepositoryRequest.Marshal(b, m, deterministic)
}
func (m *ReplicateRepositoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateRepositoryRequest.Merge(m, src)
}
func (m *ReplicateRepositoryRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicateRepositoryRequest.Size(m)
}
func (m *ReplicateRepositoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateRepositoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateRepositoryRequest proto.InternalMessageInfo

func (m *ReplicateRepositoryRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *ReplicateRepositoryRequest) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

type ReplicateRepositoryResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicateRepositoryResponse) Reset()         { *m = ReplicateRepositoryResponse{} }
func (m *ReplicateRepositoryResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicateRepositoryResponse) ProtoMessage()    {}
func (*ReplicateRepositoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36da0b8129c7cf1c, []int{2}
}

func (m *ReplicateRepositoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateRepositoryResponse.Unmarshal(m, b)
}
func (m *ReplicateRepositoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateRepositoryResponse.Marshal(b, m, deterministic)
}
func (m *ReplicateRepositoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateRepositoryResponse.Merge(m, src)
}
func (m *ReplicateRepositoryResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicateRepositoryResponse.Size(m)
}
func (m *ReplicateRepositoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateRepositoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateRepositoryResponse proto.InternalMessageInfo

func (m *ReplicateRepositoryResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Repository)(nil), "replication.Repository")
	proto.RegisterType((*ReplicateRepositoryRequest)(nil), "replication.ReplicateRepositoryRequest")
	proto.RegisterType((*ReplicateRepositoryResponse)(nil), "replication.ReplicateRepositoryResponse")
}

func init() { proto.RegisterFile("replication/replication.proto", fileDescriptor_36da0b8129c7cf1c) }

var fileDescriptor_36da0b8129c7cf1c = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xa9, 0x88, 0xe0, 0xc4, 0xd3, 0x7a, 0xb0, 0x54, 0x44, 0xc9, 0xc5, 0x5e, 0x9a, 0xd0,
	0x56, 0xf0, 0xac, 0x3f, 0x61, 0xbd, 0x79, 0x91, 0x4d, 0x76, 0x68, 0x16, 0x6c, 0x66, 0x9d, 0x9d,
	0x04, 0xbc, 0xf8, 0xdb, 0x25, 0x9b, 0x62, 0x17, 0x89, 0x78, 0x7b, 0x7c, 0xcc, 0xbc, 0xf7, 0x86,
	0x81, 0x1b, 0x46, 0xff, 0xee, 0x6a, 0x23, 0x8e, 0xda, 0x32, 0xd1, 0x85, 0x67, 0x12, 0x52, 0x59,
	0x82, 0xf2, 0x07, 0x00, 0x8d, 0x9e, 0x82, 0x13, 0xe2, 0x4f, 0xa5, 0xe0, 0xb4, 0x0b, 0xc8, 0xf3,
	0xd9, 0xdd, 0x6c, 0x79, 0xae, 0xa3, 0x1e, 0x18, 0xa3, 0xa7, 0xf9, 0xc9, 0xc8, 0x06, 0x9d, 0xf7,
	0xb0, 0xd0, 0x07, 0x13, 0x3c, 0xae, 0x6b, 0xfc, 0xe8, 0x30, 0x88, 0x7a, 0x04, 0xe0, 0x1f, 0x18,
	0xbd, 0xb2, 0xcd, 0x55, 0x91, 0x16, 0x49, 0x76, 0x92, 0x51, 0x75, 0x0b, 0x19, 0xe3, 0x9e, 0x04,
	0xdf, 0x8c, 0xb5, 0x7c, 0x48, 0x84, 0x11, 0x3d, 0x59, 0xcb, 0xf9, 0x1a, 0xae, 0x27, 0x73, 0x83,
	0xa7, 0x36, 0xe0, 0x50, 0xd5, 0x1a, 0x31, 0x31, 0xf2, 0x42, 0x47, 0xbd, 0xf9, 0x02, 0xa5, 0x8f,
	0xc9, 0x2f, 0xc8, 0xbd, 0xab, 0x51, 0x35, 0x70, 0x39, 0x61, 0xa4, 0xee, 0x7f, 0xb7, 0xfc, 0xe3,
	0xc4, 0xc5, 0xf2, 0xff, 0xc1, 0xb1, 0xd3, 0xf3, 0xf6, 0x75, 0xbd, 0x73, 0xd2, 0x74, 0x55, 0x51,
	0xd3, 0xbe, 0xec, 0x7b, 0x23, 0xa6, 0x35, 0x15, 0x96, 0x3b, 0x27, 0xab, 0xc6, 0xac, 0x3c, 0xd5,
	0x65, 0x7c, 0x4b, 0xfa, 0xa8, 0xea, 0x2c, 0xa2, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b,
	0xa2, 0xea, 0x9b, 0xca, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReplicationServiceClient is the client API for ReplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicationServiceClient interface {
	ReplicateRepository(ctx context.Context, in *ReplicateRepositoryRequest, opts ...grpc.CallOption) (*ReplicateRepositoryResponse, error)
}

type replicationServiceClient struct {
	cc *grpc.ClientConn
}

func NewReplicationServiceClient(cc *grpc.ClientConn) ReplicationServiceClient {
	return &replicationServiceClient{cc}
}

func (c *replicationServiceClient) ReplicateRepository(ctx context.Context, in *ReplicateRepositoryRequest, opts ...grpc.CallOption) (*ReplicateRepositoryResponse, error) {
	out := new(ReplicateRepositoryResponse)
	err := c.cc.Invoke(ctx, "/replication.ReplicationService/ReplicateRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServiceServer is the server API for ReplicationService service.
type ReplicationServiceServer interface {
	ReplicateRepository(context.Context, *ReplicateRepositoryRequest) (*ReplicateRepositoryResponse, error)
}

// UnimplementedReplicationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReplicationServiceServer struct {
}

func (*UnimplementedReplicationServiceServer) ReplicateRepository(ctx context.Context, req *ReplicateRepositoryRequest) (*ReplicateRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicateRepository not implemented")
}

func RegisterReplicationServiceServer(s *grpc.Server, srv ReplicationServiceServer) {
	s.RegisterService(&_ReplicationService_serviceDesc, srv)
}

func _ReplicationService_ReplicateRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).ReplicateRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/replication.ReplicationService/ReplicateRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).ReplicateRepository(ctx, req.(*ReplicateRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReplicationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "replication.ReplicationService",
	HandlerType: (*ReplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicateRepository",
			Handler:    _ReplicationService_ReplicateRepository_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "replication/replication.proto",
}
