verbose: true
port: 50051
dsn: root:deadbeef@tcp(db:3306)/git-ha-poc
zones:
  - name: midgar
    nodes:
      - addr: tadpole-1-a:50051
        writable: true
      - addr: tadpole-2-a:50051
        writable: false
      - addr: tadpole-3-b:50051
        writable: false
  - name: goldsaucer
    nodes:
      - addr: tadpole-4-a:50051
        writable: true
      - addr: tadpole-5-a:50051
        writable: false
      - addr: tadpole-6-b:50051
        writable: false
users:
  - name: foo
    zone: midgar
  - name: bar
    zone: midgar
  - name: baz
    zone: goldsaucer